In [1]:
import numpy as np 
#Basic 1D array
array = np.array([1,2,3,4,5,6,7,8,9,10])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
#2D array
t_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
t_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
#Arange 
arange = np.arange(0,20,5)
arange

array([ 0,  5, 10, 15])

In [17]:
#syntax for 1d zeros-> np.zeros(zeros how many time)
#syntax for 2d zeros-> np.zeros((which dimension, zeros how many times))
zeros = np.zeros(10)
print("Simple 10 zeroes:" ,zeroes)
t_zeros = np.zeros((2,5))
print("2d zeroes:" ,t_zeros)

Simple 10 zeroes: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2d zeroes: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
#syntax -> np.full(how many time,which number)
#syntax 2D -> np.full((which dimension, how many times),which number)
full = np.full(10,6)
print("Simple: ",full)
itr_full = np.full((2,10),7)
print("2D no 7 repeated 10 times: ",itr_full)

Simple:  [6 6 6 6 6 6 6 6 6 6]
2D no 7 repeated 10 times:  [[7 7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7 7]]


In [21]:
#converting python list to np array
list = [1,2,3,4,5,6]
to_numpyArr = np.array(list)
print("Converted to list successfully: ",to_numpyArr)

Converted to list successfully:  [1 2 3 4 5 6]
