In [2]:
import numpy as np 
arr = np.array([1,2,3,4,5,16,17,18,19])
find = np.where(arr > 5)
print(find)

(array([5, 6, 7, 8], dtype=int64),)


In [11]:
print(f'the indexes are:\n{find[0]}\n and the numbers are:\n{arr[find[0]]}')

the indexes are:
[5 6 7 8]
 and the numbers are:
[16 17 18 19]
