In [14]:
import numpy as np
#1D array slicing practice
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original Array:", arr)
print("1-5 elements of Array:", arr[0:5])
print("last three elements of Array:", arr[-3:])
print("every second elements of Array:", arr[1::2])
print("reverse of Array:", arr[::-1])
print("every second from 2-7 elements of Array:", arr[2:7:2])

Original Array: [ 10  20  30  40  50  60  70  80  90 100]
1-5 elements of Array: [10 20 30 40 50]
last three elements of Array: [ 80  90 100]
every second elements of Array: [ 20  40  60  80 100]
reverse of Array: [100  90  80  70  60  50  40  30  20  10]
every second from 2-7 elements of Array: [30 50 70]


In [48]:
#2D array slicing practice, syntax-> [row slice, column slice]
arr_2d = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

print("Original 2D Array:\n", arr_2d)
print("first row of  2D Array:\n", arr_2d[0:1])
print("last column 2D Array:\n", arr_2d[:,-1])
print("first two rows and first three columns 2D Array:\n", arr_2d[:2,:3])
print("all rows but only 2nd and 3rd column 2D Array:\n", arr_2d[:,1:3])
print("reverse rows of 2D Array:\n", arr_2d[::-1,:])
print("reverse column of 2D Array:\n", arr_2d[:,::-1])

Original 2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
first row of  2D Array:
 [[1 2 3 4 5]]
last column 2D Array:
 [ 5 10 15 20]
first two rows and first three columns 2D Array:
 [[1 2 3]
 [6 7 8]]
all rows but only 2nd and 3rd column 2D Array:
 [[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]
reverse rows of 2D Array:
 [[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
reverse column of 2D Array:
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]


In [11]:
import numpy as np
#3D array slicing
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]]])
array_3d
print("1st layer:\n ",array_3d[0])
print("Extracting row from a specific layer:\n",array_3d[0,1])
print("Extracting a specific element from a specific layer and row:\n",array_3d[0,0,1])
print("Slicing across all layers, selecting specific rows and columns:\n",array_3d[:, 0:2, 1:3])


1st layer:
  [[1 2 3]
 [4 5 6]]
Extracting row from a specific layer:
 [4 5 6]
Extracting a specific element from a specific layer and row:
 2
Slicing across all layers, selecting specific rows and columns:
 [[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]
