In [3]:
import numpy as np 
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshape_np1 = np1.reshape(3,4)
reshape_np1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
reshaping_n4 = np1.reshape(2,3,2)
reshaping_n4

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [6]:
reshaping_n4 = reshaping_n4.reshape(-1)
reshaping_n4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
one = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
two = np.array([[1,2,3,4,5],[6,7,8,9,10]])
three = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(f"Shape of 1D: {one.shape}\nShape of 2D: {two.shape}\nShape of 3D: {three.shape}")
print(f'Array {one} reshaped to 2D:\n{one.reshape(3,4)}')
print(f'Array {one} reshaped to 3D:\n{one.reshape(2,2,3)}')

Shape of 1D: (12,)
Shape of 2D: (2, 5)
Shape of 3D: (1, 4, 3)
Array [ 1  2  3  4  5  6  7  8  9 10 11 12] reshaped to 2D:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array [ 1  2  3  4  5  6  7  8  9 10 11 12] reshaped to 3D:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
